#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2020-present Fewtarius

###
### Simple script to build AmberELEC
###

if [ -z "${ADD_ARM}" ]
then
  echo "NO ARM PACKAGES SPECIFIED."
  exit 0
fi

if [ !"${DEVICE}" == true ]
then
  echo "export DEVICE before building."
  exit 1
fi

if [ !"${ARCH}" == true ]
then
  echo "export ARCH before building."
  exit 1
fi

# Clean a few packages to ensure the build date and version are updated
for package in emuelec u-boot ${ADD_ARM}
do
  ./scripts/clean ${package}
done

if [ "${ARCH}" == "arm" ]
then
  # emulationstation retroarch retrorun pcsx_rearmed parallel-n64 SDL2 SDL2_image SDL2_mixer SDL2_net SDL2_ttf SDL2_gfx
  # Only build the 32bit packages that we need rather than the whole image
  # to speed up the build process and save disk space.
  for package in gcc ${ADD_ARM} 
  do
    scripts/build ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  
    scripts/install ${package}
    if [ ! $? == 0 ]
    then
      echo "Build failed..exiting."
      exit 1
    fi
  done
fi

if [ ! $? == 0 ]
then
  echo "Build failed..exiting."
  exit 1
fi

#exit 1
#BUILD="build.EmuELEC-${DEVICE}.arm-*"
#rm -rf ./${BUILD}
